[config] .Files.Glob fails with an error instead of a warning message if no matches found
```
Error: unable to load werf config: template: werfConfig:8:9: executing "werfConfig" at <.Files.Glob>: error calling Glob: {{ .Files.Glob "path" }}: no matches found
```