Fix GetStageDescription when docker registry repo is not exist
Error: reading image "docker.pkg.github.com/user/repo/stages:de07eea0119baca706320aa6b7f32f887f5700b6fd82e1864867a1ee-1590064872402": GET
https://docker.pkg.github.com/v2/user/repo/stages/manifests/de07eea0119baca706320aa6b7f32f887f5700b6fd82e1864867a1ee-1590064872402: NAME_UNKNOWN: docker package "stages" does not exist under owner "user/repo"